[package]
name = "grusp"
version = "0.1.0"
authors = ["Kevin Choubacha <kchoubacha@weedmaps.com>"]

[dependencies]
clap = "2.27"
atty = "0.2"
rayon = "0.9"
regex = "0.2"
grusp-core = { path = "grusp-core" }

[workspace]

[dev-dependencies]
assert_cli = "0.5"