[package]
name = "grusp"
version = "0.1.0"
authors = ["Kevin Choubacha <kchoubacha@weedmaps.com>"]

[dependencies]
clap = "2.27"
regex = "0.2"
glob = "0.2"
colored = "1.6"
rayon = "0.9"

[dev-dependencies]
assert_cli = "0.5"
