version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Test Library
          command: cargo test --manifest-path=grusp-core/Cargo.toml
      - run:
          name: Test Binary
          command: cargo test
